# Generated by Django 5.2.2 on 2025-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0024_laptop_ai_chip_laptop_extra_features_laptop_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
