# Generated by Django 5.2.2 on 2025-09-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0025_laptop_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='os_type',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='sold',
        ),
        migrations.AddField(
            model_name='laptop',
            name='os',
            field=models.CharField(default='Windows', max_length=100),
        ),
    ]
