# Generated by Django 5.2.2 on 2025-09-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0026_remove_laptop_os_type_remove_laptop_sold_laptop_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptop',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
